<?php
  $arSettings=[
    "IB"=>[
      "designer_settings"=>7,
      "designer_menu_top_1"=>4,
      "designer_menu_top_2"=>5,
      "designer_menu_bottom"=>6,
      "slider_1"=>8,
      "articles_1"=>9,
      "contacts"=>10,
      "faq"=>11,
      "reviews_prod"=>14,
      "1c_catalog"=>12,
      "1c_offers"=>13,
      "cabinet_1"=>15
    ],
    "LINK_STATIC"=>[
      "articles_list"=>"/articles/",
      "catalog"=>"/catalog/",
    ],
    "SHOP"=>[
      "API_KEY_PHONE_SENDER"=>"bfe361e91574187e5c6cf0e58b340b74",
      "BASE_PRICE_CODE"=>3,
      "BASE_CURR_CODE"=>"RUB",
      "SECTION"=>[
        "kupalniki"=>"Купальники",
      ],
    ],
    "COLOR_1"=>[
      "Голубой"=>"#42aaff",
      "Белый"=>"#fff",
      "Черно-бежевый"=>"#a49e77",
      "Винный"=>"#7b0323",
      "Черный"=>"#000",
      "Золотой"=>"#ffd700",
      "Синий"=>"#0000ff",
      "Красный"=>"#FF0000",
      "Салатовый"=>"#99ff99",
      "Розовый"=>"#ffc0cb",
      "Бирюзовый"=>"#30d5c8",
      "Фиолетовый"=>"#8b00ff",
      "Малина"=>"#dc143c",
      "Шоколад"=>"#d2691e",
      "Хаки"=>"#806b2a",
      "Травяной зеленый"=>"#3f9b0b",
      "Изумрудный"=>"#50c878",
    ],
  ];
?>