<?php
  //Вызов компонента
  $APPLICATION->IncludeComponent(
      "swf:shop",
      "",
      [
        "arSettings"=>"",
        "IB_CAT"=>"",
        "IB_SKU"=>"",
        "IB_REW"=>"",
        "SETT_COLOR_1"=>"",
        "SETT_SHOP_1"=>"",
        "GROUP_PODOB_1"=>"",
        "GROUP_PODOB_1_PROP"=>"",
        "GROUP_PODOB_1_RAZD"=>"",
        "DETAIL_CODE"=>"",
        "SECTION_CODE_PRINT"=>"",
        "SECTION_NAME_PRINT"=>"",
        "LINK_CATALOG"=>"",
        "CART_DATA"=>"",
        "SLIDER_TITLE"=>"",
        "SLIDER_LIMIT"=>"",
        "ALL_CATALOG_CAST_TITLE"=>"",
        "BUTT_CENTER"=>"",
        "SEARCH_TEXT"=>"", //БЭК Текст поиска
      ],
    );
  }
?>